### ISSUE TITLE
Hot reloading via `createClass`

### ISSUE THREAD

**Issue by timbur** [gaearon/react-patch#1] opened 2015-05-02 22:50 UTC
Continued from https://github.com/facebook/react/issues/2797.

> The way patching works, the same makeHot function should handle both the original version of the component, and all its updated “versions” which you get from the re-evaluated module code on hot updates. This is how it knows that they all refer to the same class in code, and sets up the patching. So in your case you need to somehow store a map of makeHot functions based on some unique class identifier.

Is this because `react-hot-api` was derived from webpack and how it sends info about updated modules?  Or is it to account for possible renaming of React classes?  If the latter, would it make sense to just keep a single reference to the React class and update the methods accordingly for each reload while letting everything else pan out as usual?  I still need to dive deeper into both React and `react-hot-api`'s internals, so I'm just making some educated guesses here.

> createClass has auto-binding, and new methods after hot reload need to be auto-bound.

Can you elaborate on what exactly the auto-binding is for/what it does?  Is that referring to stuff like `<div onClick={this.handleClick}>` or something else?

**Comment by timbur** [comment] 2015-05-03 20:22
Alright, I have a pretty good understanding of how everything works now.  I'm actually trying a different approach for the hot reloading though, and it seems to work so far but needs more tests.  I may get around to submitting a PR tomorrow.  We'll see.  :)

**Comment by gaearon** [comment] 2015-05-03 23:04
>Is this because react-hot-api was derived from webpack and how it sends info about updated modules? Or is it to account for possible renaming of React classes? 

Think of a module having versions: A1, A2, A3. They aren't *actually* named differently; it's the result of executing the same code and slightly tweaked component between reloads. From JS point of view, these are completely different classes. What we are doing is *patching each of them* to point to some *A0* we have created. This way all methods in *all versions* point to the same real class. But, of course, some other component B needs to have its own B1, B2, B3, and ultimately, B0. The reason `makeHot` (or `hotify`) functions need to be stored “per component” is so that each of them can maintain its own “X0” class to which it forwards methods of each succeeding version of a component. That's why we have `getHot` keep a map of `hotify` functions per unique IDs of component classes (usually filename + class name works good). Again, it doesn't have anything to do with *renaming*: the issue is **figuring out which existing in-memory class should we proxy methods to from an arbitrary component whose definition was just evaluated during a hot reload.**

>I'm actually trying a different approach for the hot reloading though, and it seems to work so far but needs more tests. I may get around to submitting a PR tomorrow. We'll see. :)

Sure, let me know!

>Can you elaborate on what exactly the auto-binding is for/what it does? Is that referring to stuff like <div onClick={this.handleClick}> or something else?

Yes. In `createStyle`-style classes, methods are autobound. They get `this` value even if you call them like you wrote. Because autobinding happens during instance construction, if you slap a method on top of the prototype *after an instance was created* (pretty much what hot reloading does), it won't be autobound. Bummer! The correct behavior is to re-execute autobinding code *for that component instance*, just like it happens during component construction. [Calling this function](https://github.com/gaearon/react-hot-api/blob/master/modules/bindAutoBindMethods.js#L45) on [all mounted component instances](https://github.com/gaearon/react-hotify/blob/master/src/makeHotify.js#L61) should do the job.

**Comment by timbur** [comment] 2015-05-04 13:03
@gaearon Thanks for the info.  Makes sense!

A bit about myself: I actually created a component system with hot reloading roughly a year before React started gaining traction, but I never had the time to spread the word, plus the timing probably wasn't right and I'm obviously not Facebook with billions of dollars and tons of hype around my name.  I've been a long-time GitHub/OSS lurker and decided recently that the best thing to do now is join in on the fun and ride the React wave.  It's been a pleasure so far.  :)

But back to the matter at hand.  As you can probably see from the latest pull requests, I basically ported `react-hot-api`'s `createClass` patching to `react-hotify` and modified it slightly so that it tracks and uses the `mountedInstances`.  I actually tried the same `proxy` decorator method on `createClass` and it was functioning seemingly perfectly, but React was displaying warning messages about `getInitialState` being attached to the wrong type of prototype.

To elaborate, I created two different `HotClass`es, one for the plain ES6 classes and another for `React.createClass`, and proxied the methods accordingly.  The idea was to support the ability to go back and forth between the two if someone wanted (albeit probably really unnecessary).  Again, this worked but I didn't like the warnings about `getInitialState` that React was displaying, so I just said forget it and went with what I know works from the `react-hot-api`, as I really don't have time right now to continue working on it.  Optimization and `createClass` testes can come later, but for now, as long as it (mostly) works, that's all I need.

**Comment by gaearon** [comment] 2015-05-04 13:35
Thanks! I'll take a closer look later today.

>but React was displaying warning messages about getInitialState being attached to the wrong type of prototype.

Here's how to fix it: https://github.com/gaearon/react-hot-api/blob/master/modules/makeAssimilatePrototype.js#L31-L33

**Comment by gaearon** [comment] 2015-07-08 21:09
This is still an issue, why close it?
I'm not accepting the PR because I want to have a clean way to fix it, not copy pasted code :-)

**Comment by gaearon** [comment] 2015-07-08 21:10
I'll probably be able to go back to it this or next month.

**Comment by timbur** [comment] 2015-07-08 21:53
Understandable.  At the time, I just needed something that I could easily use as a babel plugin.  The proxy method currently has some issues though, so I'm creating a babel plugin using your `react-hot-api` instead... or does that already exist and I just couldn't find it?

**Comment by gaearon** [comment] 2015-07-08 22:24
There is only Babel plugin for `react-hotify`.

**Comment by timbur** [comment] 2015-07-09 02:06
I made [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) today.  It's definitely rough around the edges but I'll thoroughly test it tomorrow.  I'm an AST noob so I had to resort to a bit of a hack to make it work for `React.createClass` in the short term.  Hopefully someone at babel/babel#1955 can show me the best way to do it.

**Comment by gaearon** [comment] 2015-07-09 13:53
Awesome. Thanks a lot.

**Comment by timbur** [comment] 2015-08-04 03:30
Hey, just letting you know I made [`webpack-module-hot-accept`](https://github.com/loggur/webpack-module-hot-accept) so you don't waste your time making something similar to work alongside your `babel-plugin-react-hotify` if/when you resume work on it.

**Comment by gaearon** [comment] 2015-08-11 10:12
Thanks!

**Comment by gaearon** [comment] 2015-08-18 22:08
Let's track this in https://github.com/gaearon/react-patch/pull/6

**Closed by gaearon** 2015-08-18 22:08 UTC
